//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grados
    {
        public grados()
        {
            this.grupos = new HashSet<grupos>();
            this.logros = new HashSet<logros>();
        }
    
        public string id_grado { get; set; }
        public string nom_grado { get; set; }
    
        public virtual ICollection<grupos> grupos { get; set; }
        public virtual ICollection<logros> logros { get; set; }
    }
}
