//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class logros
    {
        public logros()
        {
            this.notas = new HashSet<notas>();
        }
    
        public string id_logro { get; set; }
        public string descripcion { get; set; }
        public string id_grado { get; set; }
        public string id_asignatura { get; set; }
    
        public virtual asignatura asignatura { get; set; }
        public virtual grados grados { get; set; }
        public virtual ICollection<notas> notas { get; set; }
    }
}
