//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPL_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class areas
    {
        public areas()
        {
            this.asignatura = new HashSet<asignatura>();
        }
    
        public string id { get; set; }
    
        public virtual ICollection<asignatura> asignatura { get; set; }
    }
}
