//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPL_APP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdsigameEntities : DbContext
    {
        public bdsigameEntities()
            : base("name=bdsigameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<areas> areas { get; set; }
        public DbSet<asignatura> asignatura { get; set; }
        public DbSet<bitacora> bitacora { get; set; }
        public DbSet<directores_g> directores_g { get; set; }
        public DbSet<grados> grados { get; set; }
        public DbSet<grupos> grupos { get; set; }
        public DbSet<horarios> horarios { get; set; }
        public DbSet<jornadas> jornadas { get; set; }
        public DbSet<logros> logros { get; set; }
        public DbSet<matricula1> matricula1 { get; set; }
        public DbSet<matricula2> matricula2 { get; set; }
        public DbSet<notas> notas { get; set; }
        public DbSet<observatorio> observatorio { get; set; }
        public DbSet<periodos> periodos { get; set; }
        public DbSet<personas> personas { get; set; }
        public DbSet<reportes> reportes { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
