//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPL_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodos
    {
        public periodos()
        {
            this.notas = new HashSet<notas>();
            this.observatorio = new HashSet<observatorio>();
            this.reportes = new HashSet<reportes>();
        }
    
        public string id { get; set; }
        public string rangoI { get; set; }
        public string rangoF { get; set; }
    
        public virtual ICollection<notas> notas { get; set; }
        public virtual ICollection<observatorio> observatorio { get; set; }
        public virtual ICollection<reportes> reportes { get; set; }
    }
}
