//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPL_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class jornadas
    {
        public jornadas()
        {
            this.horarios = new HashSet<horarios>();
            this.personas = new HashSet<personas>();
        }
    
        public string id { get; set; }
        public Nullable<System.TimeSpan> horaI { get; set; }
        public Nullable<System.TimeSpan> horaF { get; set; }
    
        public virtual ICollection<horarios> horarios { get; set; }
        public virtual ICollection<personas> personas { get; set; }
    }
}
