//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPL_APP
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        public personas()
        {
            this.directores_g = new HashSet<directores_g>();
            this.matricula1 = new HashSet<matricula1>();
            this.matricula2 = new HashSet<matricula2>();
            this.matricula21 = new HashSet<matricula2>();
            this.notas = new HashSet<notas>();
            this.notas1 = new HashSet<notas>();
            this.observatorio = new HashSet<observatorio>();
            this.observatorio1 = new HashSet<observatorio>();
            this.reportes = new HashSet<reportes>();
        }
    
        public string id { get; set; }
        public string id_tipo { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string telefono2 { get; set; }
        public string cel { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public string direccion2 { get; set; }
        public string sexo { get; set; }
        public string rol { get; set; }
        public string rol_secundario { get; set; }
        public string rol_terciario { get; set; }
        public string edad { get; set; }
        public string jornada { get; set; }
        public Nullable<System.DateTime> f_naci { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
    
        public virtual ICollection<directores_g> directores_g { get; set; }
        public virtual jornadas jornadas { get; set; }
        public virtual ICollection<matricula1> matricula1 { get; set; }
        public virtual ICollection<matricula2> matricula2 { get; set; }
        public virtual ICollection<matricula2> matricula21 { get; set; }
        public virtual ICollection<notas> notas { get; set; }
        public virtual ICollection<notas> notas1 { get; set; }
        public virtual ICollection<observatorio> observatorio { get; set; }
        public virtual ICollection<observatorio> observatorio1 { get; set; }
        public virtual ICollection<reportes> reportes { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual roles roles { get; set; }
    }
}
