//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignatura
    {
        public asignatura()
        {
            this.horarios = new HashSet<horarios>();
            this.logros = new HashSet<logros>();
            this.matricula1 = new HashSet<matricula1>();
            this.notas = new HashSet<notas>();
            this.observatorio = new HashSet<observatorio>();
        }
    
        public string id { get; set; }
        public string nombre { get; set; }
        public string horas { get; set; }
        public string area { get; set; }
    
        public virtual areas areas { get; set; }
        public virtual ICollection<horarios> horarios { get; set; }
        public virtual ICollection<logros> logros { get; set; }
        public virtual ICollection<matricula1> matricula1 { get; set; }
        public virtual ICollection<notas> notas { get; set; }
        public virtual ICollection<observatorio> observatorio { get; set; }
    }
}
