//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos
    {
        public grupos()
        {
            this.directores_g = new HashSet<directores_g>();
            this.reportes = new HashSet<reportes>();
            this.horarios = new HashSet<horarios>();
            this.matricula2 = new HashSet<matricula2>();
            this.matricula1 = new HashSet<matricula1>();
            this.notas = new HashSet<notas>();
            this.observatorio = new HashSet<observatorio>();
        }
    
        public string id_grupo { get; set; }
        public string id_aula { get; set; }
        public string id_grado { get; set; }
        public string año { get; set; }
    
        public virtual ICollection<directores_g> directores_g { get; set; }
        public virtual grados grados { get; set; }
        public virtual ICollection<reportes> reportes { get; set; }
        public virtual ICollection<horarios> horarios { get; set; }
        public virtual ICollection<matricula2> matricula2 { get; set; }
        public virtual ICollection<matricula1> matricula1 { get; set; }
        public virtual ICollection<notas> notas { get; set; }
        public virtual ICollection<observatorio> observatorio { get; set; }
    }
}
