//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas
    {
        public int referencia { get; set; }
        public string id_estudiante { get; set; }
        public string id_asignatura { get; set; }
        public string id_grupo { get; set; }
        public string id_periodo { get; set; }
        public string id_profesor { get; set; }
        public string id_logro { get; set; }
        public string nota { get; set; }
        public string nota_s { get; set; }
        public string equivalencia { get; set; }
        public string equivalencia_s { get; set; }
    
        public virtual asignatura asignatura { get; set; }
        public virtual grupos grupos { get; set; }
        public virtual logros logros { get; set; }
        public virtual personas personas { get; set; }
        public virtual periodos periodos { get; set; }
        public virtual personas personas1 { get; set; }
    }
}
