//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string id { get; set; }
        public string password { get; set; }
        public string acceso { get; set; }
        public string niu_mobil { get; set; }
    
        public virtual personas personas { get; set; }
    }
}
